select * from CustomerAddress;
select * from Product;
select * from ProductModel;
select * from Customer;
select * from Address;
select * from ProductCategory;
select Name from Product where Color = 'Black';
select * from ProductDescription;
select * from SalesOrderDetail;
select distinct City, StateProvince from Address;
